### ISSUE TITLE
Change languageContainer default folder

### ISSUE THREAD

**Issue by JeroenMBooij** [aksoftware98/multilanguages#10]
How do I change the default location, Resources, to for example wwwroot\resources?

I have tried to add the path to the AddLanguageContainer extension method
`builder.Services.AddLanguageContainer(Assembly.GetExecutingAssembly(), @"wwwroot\resources");`

But I just get an error saying it can't find the files in the Resources folder

**Comment by aksoftware98** [comment]
Thank you so much for your interest in the plugin and sorry for that 
I will simulate the scenario and get back to you very soon 

Thanks

**Comment by JeroenMBooij** [comment]
Figured it out. you have to use a '.' instead of a '\ and you have to add your assembly name'. You can also dynamically call your assembly name incase you are working with multiple assemblies.

$@"{typeof(Program).Assembly.GetName().Name}.wwwroot.resources"

**Comment by JeroenMBooij** [comment]
The issue of the error saying it can't find the files in the Resources folder comes back again when I change language.

I worte the following function to change the language:

```
[Inject] public ILanguageContainerService Localizer { get; set; }

private void SelectCulture(string culture)
        {
            if (culture == currentCulture)
                return;

            Localizer.SetLanguage(System.Globalization.CultureInfo.GetCultureInfo(culture));
        }
```

And i set my language container like so in Program.cs:
` builder.Services.AddLanguageContainer(Assembly.GetExecutingAssembly(), $@"{typeof(Program).Assembly.GetName().Name}.wwwroot.resources");`

When I change language I get this error:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: There is no language files for 'nl-NL' existing in the Resources folder within 'Portal' assembly
System.IO.FileNotFoundException: There is no language files for 'nl-NL' existing in the Resources folder within 'Portal' assembly
  at AKSoftware.Localization.MultiLanguages.LanguageContainerInAssembly.SetLanguage 
```

**Comment by aksoftware98** [comment]
Okay thanks again for mentioning, I will get back to you very soon with a solve for this issue

**Comment by JeroenMBooij** [comment]
@aksoftware98 Any update on this issue? I am still facing the same error when I change the language using the SetLanguage method from the LanguageContainerService class

**Comment by aksoftware98** [comment]
Hi again 
I'm really for being that late 
The fix will be published in the upcoming 24 hours

**Comment by aksoftware98** [comment]
Hi again 

The issue has been fixed in the last build and the repository is now up-to-date 
You can now put the resources in any folder and also you can use path like this "Test\Languages" in addition to the following "Test.Langauges" 

Thanks for being part in developing this tool

**Comment by JeroenMBooij** [comment]
@AymanMubark I tried implementing this language library in a .NET 6 Maui Blazor application, but I am getting an error saying it can't find the files in the Resources folder when I use `Localizer.SetLanguage(System.Globalization.CultureInfo.GetCultureInfo("en-US"));`  

If I don't use the SetLanguage function everything works just fine and uses my english language files, but I can't switch language

This happens when I use the default Resources folder location and when I define my own folder location. This maybe has something to do with Maui Blazor already defining a Resources folder
