### ISSUE TITLE
Question:  Interpolation support?

### ISSUE THREAD

**Issue by gerfen** [aksoftware98/multilanguages#11]
Hi,

Thanks for the great localization library!  I am curious if you have consider adding support for interpolation as can be found in libraries like [i18n](https://www.i18next.com/translation-function/interpolation)?

Thanks!

**Comment by aksoftware98** [comment]
Hi

So happy that you liked it, this feature is already under-construction, and hopefully it will be available very soon,

You can register here: [https://ahmadmozaffar.net Sign In](https://ahmadmozaffar.net/AzureADB2C/Account/SignIn) to receive an emails with all the upcoming features, and I will keep this issue opened until the feature is live.

The expected time for it is Nov 16th, 2020 

Thank you

**Comment by gerfen** [comment]
Thanks Ahmad.  I really appreciate your efforts.  :)

**Comment by aksoftware98** [comment]
Hi again 

Really sorry for not being able to serve the feature on time, but unfortunately, some much behind the schedule, I started with it but done yet, hopefully waiting for any pull request to serve it quickly, sorry again for making you wait. 
I'm doing my best to serve the best I can very soon 

:-)

Thank you

**Comment by gerfen** [comment]
New worries Ahmad.  Do you have the feature in a branch I can take look at?  I can try the complete it for you this week.

--Michael

________________________________

**Comment by aksoftware98** [comment]
Fantastic, I will give it sometime today after the work, and I will push the branch anyway either it's done or not and we can go ahead with it.

Thanks for nice suggestion

**Comment by aksoftware98** [comment]
Thanks for your patience 

The feature has been implemented successfully on the level of the library and I started to work on ignore the translation in the online translation tool, you can check the repo for and you can feel free to submit any pull request for any enhancement you can use this feature as following :
For the language file for example 

``` YAML
 WelcomeMessage: Welcome {Username} to the system  
``` 

To fill the value of 'username' from the code you can use the new indexer 
```C#
_language["WelcomeMessage", new 
{
       username = "aksoftware"
}];
```

The output is going to be as following --> Welcome aksoftware to the system 

New enhancement will be supporter, I will make sure to update the documentation and the online translation tool within 48 hours 

I will close this issue for now and for any new issue you can feel free to submit new one.

I really appreciate your contribution and suggestion
