### ISSUE TITLE
Store Language Select

### ISSUE THREAD

**Issue by walteriermano** [aksoftware98/multilanguages#2]
Hi AK , can you show me how store the new language Select ?
for Example , if i select another Language and restart application don't restore the last language selected
Thanks 
Walter

**Comment by aksoftware98** [comment]
Hi
In this case, you can the Nuget package Blazored.LocalStorage and store the chosen culture in the browser local storage and in the program.cs check if there is any stored language.
I will get back to you after a while with all the steps in details.

Thank you

**Comment by walteriermano** [comment]
Hi Ahmad
Great
Thank a lot !

**Comment by AymanMubark** [comment]
how can check the storage in program.cs

**Comment by AymanMubark** [comment]
> how can check the storage in program.cs

             var builder = WebAssemblyHostBuilder.CreateDefault(args);

            builder.Services.AddLanguageContainer(Assembly.GetExecutingAssembly(), CultureInfo.GetCultureInfo("ar-SA"));

            builder.RootComponents.Add<App>("app");

            WebAssemblyHost host = builder.Build();
            ILocalStorageService localStogrg = host.Services.GetService(typeof(ILocalStorageService)) as ILocalStorageService;
            ILanguageContainerService languageContainerService = host.Services.GetService(typeof(ILanguageContainerService)) as ILanguageContainerService;

            if (await localStogrg.ContainKeyAsync("GetCultureInfo"))
            {
                languageContainerService.SetLanguage(new CultureInfo(await localStogrg.GetItemAsStringAsync("GetCultureInfo")));
            }
          
            await host.RunAsync();

**Comment by aksoftware98** [comment]
Hi sorry for late response 
I don't recommend to this through program.cs 
The best way to do this is through creating a new component you can call it LocalizedApp.razor and it contains as following 

```razor
    <CascadingValue Value="this">
            @ChildContent
   </CascadingValue >

  [Parameter]
  public RenderFragment ChildContent { get; set; }

 // Here Store and Retrieve the language 
``` 

After creating this component go to the App.razor and surround the whole component with LocalizedApp

This is a very quick explanation, I will make sure to write a full article on my website about how to handle this tomorrow evening

**Comment by AymanMubark** [comment]
thanks

**Comment by aksoftware98** [comment]
Sorry for being late.
The work around I mentioned above is something to forget because created a new dependency for the current library called 
AKSoftware.Localization.Mutlilanguages.Blazor 
That contains a component initialization function and it handles all the states for you, it's ready I'm just testing it, the version 1.0.0 will be online anytime soon

Thanks for your patience

**Comment by AymanMubark** [comment]
That's great will working with dotnet 5 !?

**Comment by aksoftware98** [comment]
Yes for sure I built it with .NET 5, directly the preview version is ready it will be there today, all you have to do is just in each component in the OnInitialized method add the following line:
``` C# 
  protected override void OnInitialized()
 {
              language.AddLocalizedComponent(this); // That's it ;-)
 }
```

 and state of all the components will be managed automatically whenever you call the method 
``` C#
    langauge.SetLanguage(...);
```

**Comment by aksoftware98** [comment]
The new package has just been released
You can install it from here:
``` PS
Install-Package AKSoftware.MultiLanguages.Localization.Blazor
```
Now to be able to update the all components all you have to do is to add the following namespace in the _imports.razor file 

``` C#
using AKSoftware.MultiLanguages.Localization.Blazor
```

And within each localized component you need to call the OnInitialized method or OnInitializedAsync and add the following line 
``` C#
 protected override void OnInitialized()
    {
        languageContainer.InitLocalizedComponent(this);
    }
``` 
That's everything now whenever you change the language all the registered components will be updated automatically, and regarding storing the language a new sample has been published you can find it in the following link which contains a full usage of all the new features based on .NET 5.0
https://github.com/aksoftware98/multilanguages/tree/master/src/BlazorAKLocalization

I will close this issue for now, and if you figure out anything feel free to open a new one 
Thanks again for your interest
