### ISSUE TITLE
components not updating after switching language

### ISSUE THREAD

**Issue by JeroenMBooij** [aksoftware98/multilanguages#25]
When I call .SetLanguage(System.Globalization.CultureInfo.GetCultureInfo(culture)); it only updates the language in that component, but ther other components stay the same language. How do I update the language in all components?

**Comment by aksoftware98** [comment]
Hi
Are you using the _**AKSoftware.Localizatoin.MultiLanguages.Blazor**_ library as well?
if not kindly check out the following section that shows to you how to handle the state of all the component when you change the language: 
https://github.com/aksoftware98/multilanguages#start-dealing-with-components
