### ISSUE TITLE
Possibility to get all keys of language

### ISSUE THREAD

**Issue by naefp** [aksoftware98/multilanguages#26]
Is there a possibility, or do you plan to implement one, for getting all the keys of a language?

I am thinking about solutions for displaying all translation entries or for comparing language sets and find missing keys in different languages, or other functions like that.

**Comment by aksoftware98** [comment]
That's a very good point.
Really sorry for that late response, but just got time and noticed your issue.
I will make this functionality available in the mid August version 
Thanks

**Comment by naefp** [comment]
Better late than never 👍🏼 

In the meanwhile we have written our own comparing / updating tools to partly automate the management of yaml files. But yes, i think it would be a nice feature anyway.

**Comment by aksoftware98** [comment]
Thank you so much @naefp 

Could you please let me know if you are using this library in a real project?
And how do you feel about it?

**Comment by naefp** [comment]
yes, we are using it in a small blazor webassemply app with 3 languages and so far we are happy with it.

**Comment by GregFinzer** [comment]
Implemented for upcoming version 6:  https://github.com/aksoftware98/multilanguages/pull/60
