### ISSUE TITLE
AddLangaugeContainer

### ISSUE THREAD

**Issue by bartvanhoey** [aksoftware98/multilanguages#3]
Hello

I think you misspelled AddLangaugeContainer. It should be AddLanguageContainer, shouldn't it?

Best regards

Bart

**Comment by aksoftware98** [comment]
Hi Dear

Thank you so much that right

Thanks again

Kind Regards

________________________________

**Comment by aksoftware98** [comment]
The naming of the method has been fixed in the latest version released few minutes ago with the support for nested objects
Thank you so much for mentioning
