### ISSUE TITLE
Place resource file(.yml) in different assembly instead of current running assembly

### ISSUE THREAD

**Issue by MaxChang12cA** [aksoftware98/multilanguages#36]
Hi , i'm currently working on a blazor wasm project . I have multiple assembly for this project but only one running assembly , each assembly have their own resource folder with its own language yaml files , is there a way not to include every resource file in one running assembly or each assembly can have its own language container?

**Comment by aksoftware98** [comment]
Hi @MaxChang12cA 

Thank you for your suggestion, currently this feature is not available but I have listed it to make it available in the version 6.1
As it sounds very genius and important, I thought about it for a second and it actually makes a lot of sense. 

I have scheduled it for development, so I will reply to you here when it's ready and published. 

Thanks!

**Comment by GregFinzer** [comment]
Solved with PR https://github.com/aksoftware98/multilanguages/pull/63
