### ISSUE TITLE
Generate a static class with all keys to avoid using strings to access the keys

### ISSUE THREAD

**Issue by aksoftware98** [aksoftware98/multilanguages#37]
With this new feature, every time the user builds the project, the library should generate a C# static class that contains all the keys as static properties, so no need to use strings explicitly.
The result must be something like this:

**Before**
``` C#
 <h2>@Language["Home:Title"]</h2>
``` 
**After**
```C#
<h2>@Language[LanguageKeys.Home.Title]</h2>
```

**Comment by GregFinzer** [comment]
Implemented:  https://github.com/aksoftware98/multilanguages/pull/62
