### ISSUE TITLE
Nested Entries

### ISSUE THREAD

**Issue by Krackerer** [aksoftware98/multilanguages#4]
To better structure Language Files for bigger projects nested entries would be nice.

**Comment by aksoftware98** [comment]
Thank you so much for nice notice
The feature is under development it will be available in the version 3.0 that will be released next week 
Stay tuned

**Comment by aksoftware98** [comment]
Thank you again for mentioning such a feature
The feature has been implement successfully in the library and in the translator tool as well.
Version 3.0.1 is now available on Nuget 

Enjoy it and thanks for using AK MultiLanguages
