### ISSUE TITLE
5.9.1 has braking changes in the behavior when a child key is not found

### ISSUE THREAD

**Issue by naefp** [aksoftware98/multilanguages#45]
Hi, and once more, thank your for the handy library.

After updating from 5.8.0 to 5.9.1 we experienced some braking changes:
- Behavior until **5.8.0**: When a specific child key cannot be found, but the section was found, the return value was the key name of the child key within the section but without the section name. (e.g. Key "MySection:SomeChildKey" returned **"SomeChildKey"**)
- Behavior with **5.9.1**: When a specific child key cannot be found, but the section was found, the return value is now the fully qualified key path including the section name. (e.g. Key "MySection:SomeChildKey" returns now **"MySection:SomeChildKey"**, regardless if the section was found or not)

As I have seen, the code section for finding values in the key store has been rewritten due to performance improvements. But I am not sure if this braking change of behavior for unknown child keys was expected or not.

It might be an edge case, but for now this blocks me updating the library and I need to decide what to do.

Hopefully you can take a short look and let me know **if this change was expected or if its kind of a bug** and will changed back to the old behavior?

Thanks again!

**Comment by aksoftware98** [comment]
Hi @naefp 

Thank you so much for your feedback.

That's weird, I will make sure to get this fixed in the next couple hours. 

I will review it now

Thanks

**Comment by aksoftware98** [comment]
Hi @naefp 

Thank you so much again for using **AKSoftware.MutliLanguages.Localization** and for your participation in making this package better and better.

I have just released a fix for the mentioned issue, all you have to do is to upgrade the package and run your project so hopefully  you will be good no changes are needed 

The new version has the number: [5.9.11](https://www.nuget.org/packages/AKSoftware.Localization.MultiLanguages/5.9.11)

I will close this issue, in case you are still facing it feel free to open it again. 

Have a great weekend! 

Thanks,

Ahmad

**Comment by naefp** [comment]
Thank you very much, now it seems to behave like before! 👍🏼
