### ISSUE TITLE
Error when attempting to reach the Azurewebsites translation site

### ISSUE THREAD

**Issue by Stonne** [aksoftware98/multilanguages#48]
I got the following error on pc and smartphone : 
HTTP Error 500.35 - ANCM Multiple In-Process Applications in same Process . Any idea ?

**Comment by Stonne** [comment]
I tested this site on different Pc's on different networks and locations..
The translation site does not work anymore .
see error below.  Is this definitive ?
HTTP Error 500.35 - ANCM Multiple In-Process Applications in same Process
Common solutions to this issue:
Select a different application pool to create another in-process application.
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028526

**Comment by aksoftware98** [comment]
Hi @Stonne 

Thank you so much for this update

The site is now up and running 
Let me know if you have any further issue 

Happy to help.

Thanks for using AK Multilanguages, hope you are finding it useful.

**Comment by Stonne** [comment]
Hi no problem yaml is so much easier then the complicated reach files ..
Have a nice day and keep up the good work
Stonne

Op wo 21 jun. 2023 13:45 schreef Ahmad Mozaffar ***@***.***>:

**Comment by aksoftware98** [comment]
So happy to see your feedback 

Enjoy your development
