### ISSUE TITLE
Blazor .NET 8 with server and client components - Where to put Resources Folder ?

### ISSUE THREAD

**Issue by KaniSchotski** [aksoftware98/multilanguages#58]
I like the application. But with Blazor and .NET 8, I am wandering where to put the Resources folder in case you have components on the server on the one hand, and other components on the client on the other hand. Thanks for your reply. Kani.

**Comment by bertenvdb** [comment]
Same here

**Comment by GregFinzer** [comment]
Solved with PR https://github.com/aksoftware98/multilanguages/pull/63
