### ISSUE TITLE
Not working with error There is no language files existing in the Resource folder

### ISSUE THREAD

**Issue by AmirImam** [aksoftware98/multilanguages#7]
Hi,
Thanks for this great tool
There is a problem that suddenly appeared.
The app stopped and shows error "**There is no language files existing in the Resource folder within 'MY_APP' assembly**"
After install NuGet package of this tool I have added service like that 
`builder.Services.AddLanguageContainer(Assembly.GetExecutingAssembly(), CultureInfo.GetCultureInfo("ar-EG"));`
Than in component
` [Inject] public ILanguageContainerService Localizer { get; set; }`

And I wrote languages YML files like that
en-US.yml
```
Home:Home
Administration:Administration
```

ar-eg.yml
```
Home:الرئيسية
Administration:الإدارة العامة
```

**Comment by aksoftware98** [comment]
Thanks dear for reaching 

The issue related to desereralize of the YAML files there is should be a space between the and values in your language file like this 

`Home: Home`
`Administration: Administration`

`Home: الرئيسية`
`Administration: الإدارة العامة`

This will solve this issue 

Thanks for using AKSoftware.Localization
