### ISSUE TITLE
When attempting to display text in Arabic, it shows "�����".

### ISSUE THREAD

**Issue by Youssef-AhmedX** [aksoftware98/multilanguages#74]
I am attempting to use a package in my MVC project, but when I try to translate text into Arabic, it displays "�����". Is there any solution?

this is service registration in program.cs
`builder.Services.AddLanguageContainer(Assembly.GetExecutingAssembly(), folderName: "Resources", culture: new CultureInfo("ar-EG"));
`

![image](https://github.com/user-attachments/assets/cf23ec7f-8938-4728-b4ed-0f4838cc9713)

**Comment by Youssef-AhmedX** [comment]
YAML file encoding should be UTF-8 with BOM

**Comment by aksoftware98** [comment]
Hello @Youssef-AhmedX 

Thank you for the update and the issue, I will mention that in the original docs too

Thanks!
